--- #Test localhost connection
- name: Test commands
  hosts: localhost
  connection: local
  gather_facts: true #false
  tasks:
    - name: Test local action
      command: echo "hello world"
      
    - debug:
        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribu>

# Enable to troubleshooting
#    - name: Show facts available on the system
#      ansible.builtin.debug:
#        var: ansible_facts
...
