---
- name: Test commands
  hosts: localhost
  connection: local
  become: true
#  gather_facts: true
  tasks:
#    - name: Test local action
#      command: echo "hello world"

    - name: Install Your Favorite Hacking Tools
      apt:
       state: present
#       update_cache: true
       pkg:
        - apt-transport-https
        - code-oss
        - docker.io
        - docker-compose
        - dnsutils
        - dotnet-sdk-3.1
        - iptables
        - iptables-persistent
#        - kali-linux-all #fails no package
        - kali-win-kex
        - nmap
        - python-is-python2
        - sshuttle
        - tmux
        - virt-what
        - ufw


    - hosts: kali-03
      become: yes
      tasks:
    - name: Update Hostname on Kali
        lineinfile:
        path: /etc/hosts
        state: present
        regexp: '^%127.0.1.1 kali-03'
        backup: yes #may need to remove
        line: '%127.0.1.1'
     - name: Set Hostname
       command: 'hostnamectl set-hostname kali-03'
     - name: Reboot system
       command: 'reboot'




    - name: Add sudo rights for deployment user.
      lineinfile:
        dest: /etc/sudoers
        regexp: '^linus'
        line: 'linus ALL=(ALL) NOPASSWD: ALL #Managd by Ansible'
        state: present
        validate: 'visudo -cf %s'

    - name: Debian Remove no password from Admin group 
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%ADMIN ALL='
        line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s

    - name: Disable Root Access via TTY
      lineinfile:
        backup: yes
        create: yes
        path: /etc/securetty
        state: present
        line: ' /dev/null'

    - name: Create default_keys directory if it does not exist
      become: true
      ansible.builtin.file:
        path: /etc/ssh/default_keys
        state: directory
        mode: '0755'

    - name: Backup default SSH keys file 
      become: true
      ansible.builtin.copy:
        #src: /etc/ssh/ssh_host_*.* 
        src: /etc/ssh/          
        dest: /etc/ssh/default_keys    



    - name: Set permission on linus home folder
      ansible.builtin.file:
        path: /home/linus
        owner: linus
#    group: linus
        mode: '0700'

    - name: Set permission on kali home folder
      ansible.builtin.file:
        path: /home/kali
        owner: kali
        group: kali
        mode: '0700'


    - name: Create /opt/windows-extras if it does not exist
      ansible.builtin.file:
        path: /opt/windows-extras
        state: directory
        mode: '0755'

    - name: Download tightvnc
      get_url:
        url: http://www.tightvnc.com/download/1.3.10/tightvnc-1.3.10_x86.zip
        dest: /opt/windows-extras

    - name: Download Sysinternals Suite
      get_url:
        url: https://download.sysinternals.com/files/SysinternalsSuite.zip
        dest: /opt/windows-extras

    - name: Create /opt/firefox-old if it does not exist
      ansible.builtin.file:
        path: /opt/firefox-old
        state: directory
        mode: '0755'
    - name: Download firefox-old for weak SSL ciphers
      get_url:
        url: https://download-installer.cdn.mozilla.net/pub/firefox/releases/30.0/linux-x86_64/en-US/firefox-30.0.tar.bz2
        dest: /opt/firefox-old
    
    - name: Create /opt/firefox-addons if it does not exist
      ansible.builtin.file:
        path: /opt/firefox-addons
        state: directory
        mode: '0755'
    - name: Download   
      get_url:
        url: https://addons.mozilla.org/firefox/downloads/latest/1154/addon-1154-latest.xpi
        dest: /opt/firefox-addons
#https://addons.mozilla.org/firefox/downloads/latest/216803/addon-216803-latest.xpi
#https://addons.mozilla.org/firefox/downloads/latest/9780/addon-9780-latest.xpi
#https://addons.mozilla.org/firefox/downloads/latest/953/addon-953-latest.xpi
#https://addons.mozilla.org/firefox/downloads/file/308568/foxyproxy_standard-4.5.4-sm+tb+fx.xpi
#https://addons.mozilla.org/firefox/downloads/latest/1843/addon-1843-latest.xpi
#https://addons.mozilla.org/firefox/downloads/latest/92079/addon-92079-latest.xpi
#https://addons.mozilla.org/firefox/downloads/latest/462/addon-462-latest.xpi
#https://addons.mozilla.org/firefox/downloads/latest/3899/addon-3899-latest.xpi
#https://addons.mozilla.org/firefox/downloads/latest/966/addon-966-latest.xpi
#https://addons.mozilla.org/firefox/downloads/file/82987/quickjava-1.7.2-fx.xpi
#https://addons.mozilla.org/firefox/downloads/latest/1800/addon-1800-latest.xpi
#https://addons.mozilla.org/firefox/downloads/latest/355807/addon-355807-latest.xpi
#https://addons.mozilla.org/firefox/downloads/latest/410578/addon-410578-latest.xpi
#https://addons.mozilla.org/firefox/downloads/latest/262804/addon-262804-latest.xpi
#https://addons.mozilla.org/firefox/downloads/latest/300254/addon-300254-latest.xpi

    - name: Create /usr/share/wordlists if it does not exist
      ansible.builtin.file:
        path: /usr/share/wordlists
        state: directory
        mode: '0755'

#works, commenting out for speed
#    - name: get aquatone
#      git:
#        repo: https://github.com/michenriksen/aquatone
#        dest: /opt/aquatone
#        update: yes
#    - name: get lazyrecon
#      git:
#        repo: https://github.com/nahamsec/lazyrecon
#        dest: /opt/lazyrecon
#        update: 


#2021/8/25
#A:
    - name: get aquatone
      git:
        repo: https://github.com/michenriksen/aquatone
        dest: /opt/aquatone
        update: yes
    - name: get asn
      git:
        repo: https://github.com/nitefood/asn
        dest: /opt/asn
        update: yes
    - name: get asnlookup
      git:
        repo: https://github.com/yassineaboukir/asnlookup
        dest: /opt/asnlookup
        update: yes
    - name: get autoenum
      git:
        repo: https://github.com/Gr1mmie/autoenum
        dest: /opt/autoenum
        update: yes
    - name: get AutoRecon
      git:
        repo: https://github.com/Tib3rius/AutoRecon
        dest: /opt/AutoRecon
        update: yes
    - name: get avet
      git:
        repo: https://github.com/govolution/avet
        dest: /opt/avet
        update: yes


#C:
    - name: get certspotter
      git:
        repo: https://github.com/SSLMate/certspotter
        dest: /opt/certspotter
        update: yes
    - name: get CeWL
      git:
        repo: https://github.com/digininja/CeWL
        dest: /opt/CeWL
        update: yes
    - name: get CloudBrute
      git:
        repo: https://github.com/jhaddix/CloudBrute
        dest: /opt/CloudBrute
        update: yes
    - name: get Covenant
      git:
        repo: https://github.com/ZeroPointSecurity/Covenant
        dest: /opt/<repo>
        update: yes
    - name: get crtndstry
      git:
        repo: https://github.com/nahamsec/crtndstry
        dest: /opt/crtndstry
        update: yes

#D:
    - name: get dirsearch
      git:
        repo: https://github.com/maurosoria/dirsearch
        dest: /opt/dirsearch
        update: yes

    - name: get discover
      git:
        repo: https://github.com/leebaird/discover
        dest: /opt/discover
        update: yes
    - name: get dnsdumpster
      git:
        repo: https://github.com/wangoloj/dnsdumpster
        dest: /opt/dnsdumpster
        update: yes

#E:
    - name: get easysploit
      git:
        repo: https://github.com/KALILINUXTRICKSYT/easysploit
        dest: /opt/easysploit
        update: yes
    - name: get enum4linux-ng
      git:
        repo: https://github.com/cddmp/enum4linux-ng
        dest: /opt/enum4linux-ng
        update: yes
    - name: get evilportals
      git:
        repo: https://github.com/kbeflo/evilportals
        dest: /opt/evilportals
        update: yes
    - name: get exe2hex 
      git:
        repo: https://github.com/g0tmi1k/exe2hex 
        dest: /opt/exe2hex 
        update: yes

#F:
    - name: get feroxbuster
      git:
        repo: https://github.com/epi052/feroxbuster
        dest: /opt/feroxbuster
        update: yes
    - name: get fff
      git:
        repo: https://github.com/tomnomnom/fff
        dest: /opt/fff
        update: yes
    - name: get ffuf
      git:
        repo: https://github.com/ffuf/ffuf
        dest: /opt/ffuf
        update: yes
    - name: get firefox_decrypt
      git:
        repo: https://github.com/unode/firefox_decrypt
        dest: /opt/firefox_decrypt
        update: yes

#G:
    - name: get gau
      git:
        repo: https://github.com/lc/gau
        dest: /opt/gau
        update: yes
    - name: get getsploit
      git:
        repo: https://github.com/vulnersCom/getsploit
        dest: /opt/getsploit
        update: yes
    - name: get github-search
      git:
        repo: https://github.com/gwen001/github-search
        dest: /opt/github-search
        update: yes
    - name: get gospider
      git:
        repo: https://github.com/jaeles-project/gospider
        dest: /opt/gospider
        update: yes
    - name: get gowitness
      git:
        repo: https://github.com/sensepost/gowitness
        dest: /usr/bin/gowitness
        update: yes
    - name: get GTFOBLookup
      git:
        repo: https://github.com/nccgroup/GTFOBLookup
        dest: /opt/GTFOBLookup
        update: yes

#H:
    - name: get hacks
      git:
        repo: https://github.com/tomnomnom/hacks
        dest: /opt/hacks
        update: yes
    - name: get hakrawler
      git:
        repo: https://github.com/hakluke/hakrawler
        dest: /opt/hakrawler
        update: yes
    - name: get hetty
      git:
        repo: https://github.com/dstotijn/hetty
        dest: /opt/hetty
        update: yes
    - name: get httprobe
      git:
        repo: https://github.com/tomnomnom/httprobe
        dest: /opt/httprobe
        update: yes

#I:
    - name: get ike-scan
      git:
        repo: https://github.com/royhills/ike-scan
        dest: /opt/ike-scan
        update: yes
    #- name: configure ike-scan
    #  shell: autoreconf --install; ./configure --with-openssl
    #  args:
    #    chdir: /opt/ike-scan
    - name: get instashell
      git:
        repo: https://github.com/NathanLundner/instashell
        dest: /opt/instashell
        update: yes
    - name: get Interlace
      git:
        repo: https://github.com/codingo/Interlace
        dest: /opt/Interlace

#J:
#K:

#L:
    - name: get lazyrecon
      git:
        repo: https://github.com/nahamsec/lazyrecon
        dest: /opt/lazyrecon
        update: yes
    - name: get LinEnum rebootuser
      git:
        repo: https://github.com/rebootuser/LinEnum
        dest: /opt/LinEnum_rebootuser
        update: yes
    - name: get LinEnum Z3R0th-13 
      git:
        repo: https://github.com/Z3R0th-13/LinEnum
        dest: /opt/LinEnum_Z3R0th-13
        update: yes
    - name: get Linux_Exploit_Suggester
      git:
        repo: https://github.com/PenturaLabs/Linux_Exploit_Suggester
        dest: /opt/Linux_Exploit_Suggester
        update: yes
    - name: get linuxprivchecker
      git:
        repo: https://github.com/sleventyeleven/linuxprivchecker
        dest: /opt/linuxprivchecker
        update: yes

#M:
    - name: get massdns
      git:
        repo: https://github.com/blechschmidt/massdns
        dest: /opt/massdns
        update: yes
    - name: get metabigor
      git:
        repo: https://github.com/j3ssie/metabigor
        dest: /opt/metabigor
        update: yes
    - name: get meterpreterjank
      git:
        repo: https://github.com/lockfale/meterpreterjank
        dest: /opt/meterpreterjank
        update: yes 
    - name: get mimipenguin
      git:
        repo: https://github.com/huntergregal/mimipenguin
        dest: /opt/mimipenguin
        update: yes
    - name: get mitm6
      git:
        repo: https://github.com/fox-it/mitm6
        dest: /opt/mitm6
        update: yes

#N:
    - name: get navi
      git:
        repo: https://github.com/denisidoro/navi
        dest: /opt/navi
        update: yes
    - name: get nmapAutomator
      git:
        repo: https://github.com/21y4d/nmapAutomator
        dest: /opt/<repo>
        update: yes
    - name: get nmap-vulners
      git:
        repo: https://github.com/vulnersCom/nmap-vulners
        dest: /opt/nmap-vulners
        update: yes
    - name: get nuclei
      git:
        repo: https://github.com/projectdiscovery/nuclei 
        dest: /opt/nuclei
        update: yes

#O:
#- name: get OSCP-Preparation-Material
#  git:
#    repo: https://github.com/thelinuxchoice/OSCP-Preparation-Material
#    dest: /opt/OSCP-Preparation-Material
#    update: yes
#404


#P:
    - name: get peda
      git:
        repo: https://github.com/longld/peda
        dest: /opt/peda
        update: yes 
    - name: get p0wny-shell
      git:
        repo: https://github.com/flozz/p0wny-shell
        dest: /opt/p0wny-shell
        update: yes
    - name: get PayloadsAllTheThings
      git:
        repo: https://github.com/swisskyrepo/PayloadsAllTheThings
        dest: /opt/PayloadsAllTheThings
        update: yes
    - name: get pimpmykali
      git:
        repo: https://github.com/Dewalt-arch/pimpmykali
        dest: /opt/pimpmykali
        update: yes
    - name: get php-reverse-shell
      git:
        repo: https://github.com/pentestmonkey/php-reverse-shell
        dest: /opt/php-reverse-shell
        update: yes
    - name: get powercat
      git:
        repo: https://github.com/besimorhino/powercat
        dest: /opt/powercat
        update: yes
    - name: get PrivescCheck
      git:
        repo: https://github.com/itm4n/PrivescCheck
        dest: /opt/PrivescCheck
        update: yes
    - name: get privilege-escalation-awesome-scripts-suite
      git:
        repo: https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite
        dest: /opt/privilege-escalation-awesome-scripts-suite
        update: yes
    - name: get PSBits
      git:
        repo: https://github.com/gtworek/PSBits
        dest: /opt/PSBits
        update: yes
    - name: get pspy
      git:
        repo: https://github.com/DominicBreuker/pspy
        dest: /opt/pspy
        update: yes

#Q:

#R:
    - name: get recursive-gobuster
      git:
        repo: https://github.com/epi052/recursive-gobuster
        dest: /opt/recursive-gobuster
        update: yes
    - name: get requests
      git:
        repo: https://github.com/psf/requests
        dest: /opt/requests
        update: yes
    - name: get rsg
      git:
        repo: https://github.com/mthbernardes/rsg
        dest: /opt/rsg
        update: yes

#S:
#    - name: get SecLists
#      git:
#        repo: https://github.com/danielmiessler/SecLists
#        dest: /usr/share/wordlists
#        update: yes
    - name: get sherlock
      git:
        repo: https://github.com/sherlock-project/sherlock
        dest: /opt/sherlock
        update: yes
    - name: get spoofcheck
      git:
        repo: https://github.com/BishopFox/spoofcheck
        dest: /opt/spoofcheck
        update: yes
    - name: get sslscan
      git:
        repo: https://github.com/rbsec/sslscan
        dest: /opt/sslscan
        update: yes
    - name: get Sublist3r
      git:
        repo: https://github.com/aboul3la/Sublist3r
        dest: /opt/Sublist3r
        update: yes
    - name: get SUID3NUM
      git:
        repo: https://github.com/Anon-Exploiter/SUID3NUM
        dest: /opt/SUID3NUM
        update: yes

#T:
    - name: get tbhm
      git:
        repo: https://github.com/jhaddix/tbhm
        dest: /opt/tbhm
        update: yes
    - name: get the-essentials
      git:
        repo: https://github.com/blindpentester/the-essentials
        dest: /opt/the-essentials
        update: yes
    - name: get testssl
      git:
        repo: https://github.com/drwetter/testssl.sh.git
        dest: /opt/<repo>
        update: yes


#U:
    - name: get unfurl
      git:
        repo: https://github.com/tomnomnom/unfurl
        dest: /opt/unfurl
        update: yes
    - name: get unicorn
      git:
        repo: https://github.com/trustedsec/unicorn
        dest: /opt/unicorn
        update: yes

#V:

#W:
    - name: get waybackurls
      git:
        repo: https://github.com/tomnomnom/waybackurls
        dest: /opt/waybackurls
        update: yes
    - name: get wesng
      git:
        repo: https://github.com/bitsadmin/wesng
        dest: /opt/wesng
        update: yes
    - name: get winPEAS
      git:
        repo: https://github.com/carlospolop/PEASS-ng/tree/master/winPEAS
        dest: /opt/winPEAS
        update: yes
#    - name: get Wordlists ZephrFish
#      git:
#        repo: https://github.com/ZephrFish/Wordlists
#        dest: /usr/share/wordlists
#        update: yes
#- name: get wpscan (requires `gem install bundler && bundle install`)
#  git:
#    repo: https://github.com/wpscanteam/wpscan
#    dest: /opt/wpscan
#    update: yes